/*
javascript:(function(){try{let input=prompt("Pegá los DNIs (separados por coma, espacio o salto de línea):");if(!input)return;let dnis=input.match(/\d+/g);if(!dnis||dnis.length===0){alert("No se detectaron DNIs válidos.");return;}let dniSet=new Set(dnis.map(d=>d.trim()));let alumnos=document.querySelectorAll('.box-asistencia');if(!alumnos.length){alert("No se encontraron alumnos en pantalla.");return;}let marcados=0;let noEncontrados=new Set(dniSet);alumnos.forEach(alumno=>{try{let nodoDni=alumno.querySelector('.info.pull-right div:not(.truncate)');if(!nodoDni)return;let dni=nodoDni.textContent.replace(/\D/g,'');if(dniSet.has(dni)){noEncontrados.delete(dni);if(alumno.classList.contains('ausente')){alumno.click();marcados++;alumno.style.outline="3px solid #00c853";alumno.style.backgroundColor="#e8f5e9";}else{console.log("Ya estaba presente:",dni);}}}catch(e){console.warn("Error procesando alumno:",e);}});console.log("DNIs ingresados:",[...dniSet]);console.log("No encontrados:",[...noEncontrados]);alert("✔ Marcados: "+marcados+"\n❌ No encontrados: "+noEncontrados.size);}catch(e){alert("Error ejecutando script. Ver consola.");console.error(e);}})();

javascript:(function(){try{let input=prompt("Pegá los DNIs (separados por coma, espacio o salto de línea):");if(!input)return;let dnis=input.match(/\d+/g);if(!dnis||dnis.length===0){alert("No se detectaron DNIs válidos.");return;}let dniSet=new Set(dnis.map(d=>d.replace(/\D/g,'')));let alumnos=document.querySelectorAll('.box-asistencia');if(!alumnos.length){alert("No se encontraron alumnos en pantalla.");return;}let marcados=0;let noEncontrados=new Set(dniSet);alumnos.forEach(alumno=>{try{let nodoDni=alumno.querySelector('.info.pull-right div:not(.truncate)');if(!nodoDni)return;let dni=nodoDni.textContent.replace(/\D/g,'');if(dniSet.has(dni)){noEncontrados.delete(dni);if(alumno.classList.contains('ausente')){alumno.click();marcados++;alumno.style.outline="3px solid #00c853";alumno.style.backgroundColor="#e8f5e9";}else{console.log("Ya estaba presente:",dni);}}}catch(e){console.warn("Error procesando alumno:",e);}});console.log("DNIs ingresados:",[...dniSet]);console.log("No encontrados:",[...noEncontrados]);alert("✔ Marcados: "+marcados+"\n❌ No encontrados: "+noEncontrados.size);}catch(e){alert("Error ejecutando script. Ver consola.");console.error(e);}})();

javascript:(function(){try{let input=prompt("Pegá los DNIs:");if(!input)return;let dnis=input.match(/\d+/g);if(!dnis||dnis.length===0){alert("No se detectaron DNIs.");return;}let dniSet=new Set(dnis.map(d=>d.replace(/\D/g,'')));let alumnos=document.querySelectorAll('.box-asistencia');if(!alumnos.length){alert("No hay alumnos en pantalla.");return;}let marcados=0;let noEncontrados=new Set(dniSet);alumnos.forEach(alumno=>{try{let texto=alumno.innerText||"";let encontrados=texto.match(/\d{7,8}/g);if(!encontrados)return;encontrados.forEach(dni=>{dni=dni.replace(/\D/g,'');if(dniSet.has(dni)){noEncontrados.delete(dni);if(alumno.classList.contains('ausente')){alumno.click();marcados++;alumno.style.outline="3px solid #00c853";alumno.style.backgroundColor="#e8f5e9";}else{console.log("Ya presente:",dni);}}});}catch(e){console.warn("Error:",e);}});console.log("No encontrados:",[...noEncontrados]);alert("✔ Marcados: "+marcados+"\n❌ No encontrados: "+noEncontrados.size);}catch(e){alert("Error ejecutando script");console.error(e);}})();

35 220 734, 46.207.894, 41575157

*/
